---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pzttsfca/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
